### ISSUE TITLE
deploy properly

### ISSUE THREAD

**Issue by ungentilgarcon** [topogram/topogram#1]
we need to implement a strategy that allows perfect server deployement

**Comment by clemsos** [comment]
see here : https://github.com/topogram/topogram-client-deploy

**Comment by clemsos** [comment]
Basically 
- git clone
- meteor build  
- forever 
- supervisor / supervisorctl 
  (see https://github.com/clemsos/flask-fabric-deploy )

**Comment by ungentilgarcon** [comment]
SUCCESS:
demeteorizer --output <REP OUTPUT>

export PORT=3000
export ROOT_URL='https://app.topogram.io'
export MONGO_URL=*******_:**_*@mongodb://localhost:27017/topogram

then  forever main.js

**Comment by ungentilgarcon** [comment]
./scriptStartupTopogram.sh  
"
#!/bin/bash

export ROOT_URL='https://app.topogram.io'
export MONGO_URL='RRRR:RRRR@mongodb://localhost:27017/topogram'
export PORT=3000

forever start /home/topogram/my-meteor-deployment/bundle/main.js

"

**Comment by clemsos** [comment]
This still looks interesting - and less pain

**Comment by clemsos** [comment]
check https://github.com/ungentilgarcon/Degiteor

**Comment by clemsos** [comment]
As a reminder, here is the posts I used to deploy meteor with Docker

https://medium.com/@fermuch/meteor-1-3-docker-the-right-way-9b3ab9cc9403#.m38dn210w

http://markshust.com/2016/02/01/creating-custom-production-docker-image-meteor-13
