### ISSUE TITLE
Blank line at the end of CSV text field cause error during import 

### ISSUE THREAD

**Issue by clemsos** [topogram/topogram#104]
We should ignore the blank lines in the textarea

![selection_160](https://cloud.githubusercontent.com/assets/743246/16809221/c63e4f9c-491f-11e6-8b62-c149edad0bb8.png)

**Comment by MAKIO135** [comment]
this problem is present from the start of topogram but was once resolved by checking last line of the file

**Comment by clemsos** [comment]
Yep, it should actually filter all blank lines, unsure hwy it doesn't though https://github.com/topogram/topogram/blob/bd1b42a22859b1929a1574f1163a244804b1008a/imports/ui/pages/import.js#L27

**Comment by clemsos** [comment]
actually this is a bug from the parser ( papaparse ! ) https://github.com/mholt/PapaParse/issues/161
seems addressed already, so I will see what we can do
