### ISSUE TITLE
allow robomongolike feature for client side minimongo

### ISSUE THREAD

**Issue by ungentilgarcon** [topogram/topogram#14]
it would speed up dev

**Comment by clemsos** [comment]
solved
http://stackoverflow.com/questions/27190633/robomongo-connection-with-meteor-mongodb
http://stackoverflow.com/questions/25475975/connect-to-meteor-using-robomongo

source https://www.google.fr/search?num=30&safe=off&espv=2&q=robomongo+meteor&oq=robomongo+meteor&gs_l=serp.3..0i19l2.2333.3156.0.3297.7.3.0.4.4.0.92.92.1.1.0....0...1c.1.64.serp..2.5.98.f8N__NSpc5A

**Comment by clemsos** [comment]
not a topogram-client issue. closing

**Comment by ungentilgarcon** [comment]
then implement this: https://github.com/gterrono/houston

**Comment by clemsos** [comment]
open a new issue/feature request for that. closing again
