### ISSUE TITLE
colors not parsed

### ISSUE THREAD

**Issue by ungentilgarcon** [topogram/topogram#143]
setting color via API doesn't seem to work (like #ffffff)

**Comment by clemsos** [comment]
Color are parsed here :  
https://github.com/topogram/topogram/blob/83274914c56b36a89b677eed7abbbde200aac323/imports/ui/components/network/networkMethods.js#L204

in this order 
* color by group if group is specified 
* color if color is specified 
* yellow if the node is starred

**Comment by ungentilgarcon** [comment]
fixed with latest commits
