### ISSUE TITLE
Support time filtering for edges

### ISSUE THREAD

**Issue by ungentilgarcon** [topogram/topogram#161]
We need to investigate this issue, I checked and all nodes/edges are created...
edges are there, yet they don't get represented.
@clemsos , ex: on "Foo Fighters with edge color4"

search for edges 
db.getCollection('edges').find({'data.source' : "bogart-s39-84" })

edge is there, yet doesn"t show up....
Und ich frage mich warum????

**Comment by clemsos** [comment]
cannot reproduce the problem... Also can you share "Foo Fighters with edge color4" publicly?

Mongo / Server
![selection_304](https://user-images.githubusercontent.com/743246/32077903-47c9652c-baa5-11e7-848e-7addbbd06c02.png)

Client
![selection_302](https://user-images.githubusercontent.com/743246/32077852-1c5f4d52-baa5-11e7-823c-02bd28d0652e.png)

UI
![selection_303](https://user-images.githubusercontent.com/743246/32077848-1892936e-baa5-11e7-8538-28e3c994c424.png)

**Comment by clemsos** [comment]
From your example using "bogart-s39-84" : the 4 edges are there.

![selection_305](https://user-images.githubusercontent.com/743246/32078041-b87d6282-baa5-11e7-8ad6-093448790f3b.png)

![selection_306](https://user-images.githubusercontent.com/743246/32078062-d0686d06-baa5-11e7-8eab-1fd7f2286c75.png)

**Comment by ungentilgarcon** [comment]
here is the begining of the list of edges created, see the rpoblem if you compare it to what's displayed?
Foo Fighters
#7f3f3f
1
{'end': '2017-10-27T01:12:39', 'target': 'satyricon45-122', 'start': '1995-02-19T19:00:00', 'color': '#7f3f3f', 'notes': 'distance :233.02 km\ndatesource:', 'source': 'boat-house47-122'}
2
{'end': '2017-10-27T01:12:39', 'target': 'spaceland34-118', 'start': '1995-03-03T19:00:00', 'color': '#7f3f3f', 'notes': 'distance :1323.85 km\ndatesource:', 'source': 'satyricon45-122'}
#727f3f
0
{'end': '2017-10-27T01:12:39', 'target': 'bottleneck38-95', 'start': '1995-05-19T19:00:00', 'color': '#727f3f', 'notes': 'distance :1739.01 km\ndatesource:', 'source': 'spaceland34-118'}
1
{'end': '2017-10-27T01:12:39', 'target': 'mississippi-nights38-90', 'start': '1995-04-17T19:00:00', 'color': '#727f3f', 'notes': 'distance :440.42 km\ndatesource:', 'source': 'bottleneck38-95'}
2
{'end': '2017-10-27T01:12:39', 'target': 'bogart-s39-84', 'start': '1995-04-18T19:00:00', 'color': '#727f3f', 'notes': 'distance :495.3 km\ndatesource:', 'source': 'mississippi-nights38-90'}
3
{'end': '2017-10-27T01:12:39', 'target': 'masquerade33-84', 'start': '1995-04-19T19:00:00', 'color': '#727f3f', 'notes': 'distance :596.99 km\ndatesource:', 'source': 'bogart-s39-84'}
4
{'end': '2017-10-27T01:12:39', 'target': '40-watt-club33-83', 'start': '1995-04-21T19:00:00', 'color': '#727f3f', 'notes': 'distance :96.28 km\ndatesource:', 'source': 'masquerade33-84'}
5
{'end': '2017-10-27T01:12:39', 'target': 'cat-s-cradle35-79', 'start': '1995-04-22T19:00:00', 'color': '#727f3f', 'notes': 'distance :449.42 km\ndatesource:', 'source': '40-watt-club33-83'}
6
{'end': '2017-10-27T01:12:39', 'target': 'black-cat38-77', 'start': '1995-04-24T19:00:00', 'color': '#727f3f', 'notes': 'distance :376.68 km\ndatesource:', 'source': 'cat-s-cradle35-79'}
7
{'end': '2017-10-27T01:12:39', 'target': 'trocadero-theatre39-75', 'start': '1995-04-25T19:00:00', 'color': '#727f3f', 'notes': 'distance :200.09 km\ndatesource:', 'source': 'black-cat38-77'}
8
{'end': '2017-10-27T01:12:39', 'target': 'tramps40-74', 'start': '1995-04-26T19:00:00', 'color': '#727f3f', 'notes': 'distance :129.15 km\ndatesource:', 'source': 'trocadero-theatre39-75'}
9
{'end': '2017-10-27T01:12:39', 'target': 'tramps40-74', 'start': '1995-04-27T19:00:00', 'color': '#727f3f', 'notes': 'distance :0.0 km\ndatesource:', 'source': 'tramps40-74'}
10
{'end': '2017-10-27T01:12:39', 'target': 'lupo-s-heartbreak-hotel41-71', 'start': '1995-04-28T19:00:00', 'color': '#727f3f', 'notes': 'distance :249.7 km\ndatesource:', 'source': 'tramps40-74'}
11
{'end': '2017-10-27T01:12:39', 'target': 'avalon42-71', 'start': '1995-04-29T19:00:00', 'color': '#727f3f', 'notes': 'distance :63.88 km\ndatesource:', 'source': 'lupo-s-heartbreak-hotel41-71'}
12
{'end': '2017-10-27T01:12:39', 'target': 'opera-house43-79', 'start': '1995-04-30T19:00:00', 'color': '#727f3f', 'notes': 'distance :688.27 km\ndatesource:', 'source': 'avalon42-71'}
13
{'end': '2017-10-27T01:12:39', 'target': 'agora41-81', 'start': '1995-05-02T19:00:00', 'color': '#727f3f', 'notes': 'distance :307.65 km\ndatesource:', 'source': 'opera-house43-79'}
14
{'end': '2017-10-27T01:12:39', 'target': 'saint-andrews-hall42-83', 'start': '1995-05-04T19:00:00', 'color': '#727f3f', 'notes': 'distance :145.0 km\ndatesource:', 'source': 'agora41-81'}
15
{'end': '2017-10-27T01:12:39', 'target': 'metro41-87', 'start': '1995-05-05T19:00:00', 'color': '#727f3f', 'notes': 'distance :384.0 km\ndatesource:', 'source': 'saint-andrews-hall42-83'}
16
{'end': '2017-10-27T01:12:39', 'target': 'barrymore-theatre43-89', 'start': '1995-05-06T19:00:00', 'color': '#727f3f', 'notes': 'distance :188.35 km\ndatesource:', 'source': 'metro41-87'}
17
{'end': '2017-10-27T01:12:39', 'target': 'first-avenue-club44-93', 'start': '1995-05-07T19:00:00', 'color': '#727f3f', 'notes': 'distance :377.14 km\ndatesource:', 'source': 'barrymore-theatre43-89'}
18
{'end': '2017-10-27T01:12:39', 'target': 'king-cat-theater47-122', 'start': '1995-05-08T19:00:00', 'color': '#727f3f', 'notes': 'distance :2245.17 km\ndatesource:', 'source': 'first-avenue-club44-93'}
19
{'end': '2017-10-27T01:12:39', 'target': 'commodore-ballroom49-123', 'start': '1995-05-11T19:00:00', 'color': '#727f3f', 'notes': 'distance :195.43 km\ndatesource:', 'source': 'king-cat-theater47-122'}
20
{'end': '2017-10-27T01:12:39', 'target': 'la-luna45-122', 'start': '1995-05-12T19:00:00', 'color': '#727f3f', 'notes': 'distance :419.39 km\ndatesource:', 'source': 'commodore-ballroom49-123'}
21
{'end': '2017-10-27T01:12:39', 'target': 'press-club38-121', 'start': '1995-05-13T19:00:00', 'color': '#727f3f', 'notes': 'distance :778.2 km\ndatesource:', 'source': 'la-luna45-122'}
22
{'end': '2017-10-27T01:12:39', 'target': 'catalyst36-122', 'start': '1995-05-15T19:00:00', 'color': '#727f3f', 'notes': 'distance :183.79 km\ndatesource:', 'source': 'press-club38-121'}
23
{'end': '2017-10-27T01:12:39', 'target': 'slim-s37-122', 'start': '1995-05-16T19:00:00', 'color': '#727f3f', 'notes': 'distance :95.73 km\ndatesource:', 'source': 'catalyst36-122'}
24
{'end': '2017-10-27T01:12:39', 'target': 'slim-s37-122', 'start': '1995-05-17T19:00:00', 'color': '#727f3f', 'notes': 'distance :0.0 km\ndatesource:', 'source': 'slim-s37-122'}
25
{'end': '2017-10-27T01:12:39', 'target': 'palace-theatre-hollywood34-118', 'start': '1995-05-18T19:00:00', 'color': '#727f3f', 'notes': 'distance :558.98 km\ndatesource:', 'source': 'slim-s37-122'}
#3f7f59
0
{'end': '2017-10-27T01:12:39', 'target': 'commodore-ballroom49-123', 'start': '1995-09-16T19:00:00', 'color': '#3f7f59', 'notes': 'distance :5698.06 km\ndatesource:', 'source': 'palace-theatre-hollywood34-118'}
1
{'end': '2017-10-27T01:12:39', 'target': 'la-luna45-122', 'start': '1995-07-20T19:00:00', 'color': '#3f7f59', 'notes': 'distance :419.39 km\ndatesource:', 'source': 'commodore-ballroom49-123'}
2
{'end': '2017-10-27T01:12:39', 'target': 'the-fillmore37-122', 'start': '1995-07-24T19:00:00', 'color': '#3f7f59', 'notes': 'distance :859.55 km\ndatesource:', 'source': 'la-luna45-122'}
3
{'end': '2017-10-27T01:12:39', 'target': 'the-roxy-theatre34-118', 'start': '1995-07-26T19:00:00', 'color': '#3f7f59', 'notes': 'distance :548.67 km\ndatesource:', 'source': 'the-fillmore37-122'}
4
{'end': '2017-10-27T01:12:39', 'target': 'american-legion-hall34-118', 'start': '1995-07-27T19:00:00', 'color': '#3f7f59', 'notes': 'distance :17.94 km\ndatesource:', 'source': 'the-roxy-theatre34-118'}
5
{'end': '2017-10-27T01:12:39', 'target': 'soma32-117', 'start': '1995-07-28T19:00:00', 'color': '#3f7f59', 'notes': 'distance :175.77 km\ndatesource:', 'source': 'american-legion-hall34-118'}
6
{'end': '2017-10-27T01:12:39', 'target': 'electric-ballroom33-112', 'start': '1995-07-29T19:00:00', 'color': '#3f7f59', 'notes': 'distance :485.47 km\ndatesource:', 'source': 'soma32-117'}
7
{'end': '2017-10-27T01:12:39', 'target': 'ogden-theater39-104', 'start': '1995-07-31T19:00:00', 'color': '#3f7f59', 'notes': 'distance :943.2 km\ndatesource:', 'source': 'electric-ballroom33-112'}
8
{'end': '2017-10-27T01:12:39', 'target': 'first-avenue-club44-93', 'start': '1995-08-02T19:00:00', 'color': '#3f7f59', 'notes': 'distance :1125.14 km\ndatesource:', 'source': 'ogden-theater39-104'}
9
{'end': '2017-10-27T01:12:39', 'target': 'metro41-87', 'start': '1995-08-04T19:00:00', 'color': '#3f7f59', 'notes': 'distance :564.63 km\ndatesource:', 'source': 'first-avenue-club44-93'}
10
{'end': '2017-10-27T01:12:39', 'target': 'saint-andrews-hall42-83', 'start': '1995-08-05T19:00:00', 'color': '#3f7f59', 'notes': 'distance :384.0 km\ndatesource:', 'source': 'metro41-87'}
11
{'end': '2017-10-27T01:12:39', 'target': 'phoenix-center43-79', 'start': '1995-08-06T19:00:00', 'color': '#3f7f59', 'notes': 'distance :332.05 km\ndatesource:', 'source': 'saint-andrews-hall42-83'}
12
{'end': '2017-10-27T01:12:39', 'target': 'the-avalon42-71', 'start': '1995-08-08T19:00:00', 'color': '#3f7f59', 'notes': 'distance :693.44 km\ndatesource:', 'source': 'phoenix-center43-79'}
13
{'end': '2017-10-27T01:12:39', 'target': 'lupo-s-heartbreak-hotel41-71', 'start': '1995-08-11T19:00:00', 'color': '#3f7f59', 'notes': 'distance :66.23 km\ndatesource:', 'source': 'the-avalon42-71'}
14
{'end': '2017-10-27T01:12:39', 'target': 'the-academy40-74', 'start': '1995-08-12T19:00:00', 'color': '#3f7f59', 'notes': 'distance :249.7 km\ndatesource:', 'source': 'lupo-s-heartbreak-hotel41-71'}
15
{'end': '2017-10-27T01:12:39', 'target': 'ed-sullivan-theater40-73', 'start': '1995-08-13T19:00:00', 'color': '#3f7f59', 'notes': 'distance :5.85 km\ndatesource:', 'source': 'the-academy40-74'}
16
{'end': '2017-10-27T01:12:39', 'target': 'trocadero39-75', 'start': '1995-08-14T19:00:00', 'color': '#3f7f59', 'notes': 'distance :134.87 km\ndatesource:', 'source': 'ed-sullivan-theater40-73'}
17
{'end': '2017-10-27T01:12:39', 'target': 'black-cat38-77', 'start': '1995-08-15T19:00:00', 'color': '#3f7f59', 'notes': 'distance :199.46 km\ndatesource:', 'source': 'trocadero39-75'}
18
{'end': '2017-10-27T01:12:39', 'target': 'newport-music-hall39-83', 'start': '1995-08-17T19:00:00', 'color': '#3f7f59', 'notes': 'distance :528.58 km\ndatesource:', 'source': 'black-cat38-77'}
19
{'end': '2017-10-27T01:12:39', 'target': 'bogart-s39-84', 'start': '1995-08-18T19:00:00', 'color': '#3f7f59', 'notes': 'distance :161.07 km\ndatesource:', 'source': 'newport-music-hall39-83'}
20
{'end': '2017-10-27T01:12:39', 'target': 'the-masquerade33-84', 'start': '1995-08-19T19:00:00', 'color': '#3f7f59', 'notes': 'distance :597.26 km\ndatesource:', 'source': 'bogart-s39-84'}
21
{'end': '2017-10-27T01:12:39', 'target': 'kiewit505', 'start': '1995-08-23T19:00:00', 'color': '#3f7f59', 'notes': 'distance :7165.07 km\ndatesource:', 'source': 'the-masquerade33-84'}
22
{'end': '2017-10-27T01:12:39', 'target': 'richfield-avenue510', 'start': '1995-08-25T19:00:00', 'color': '#3f7f59', 'notes': 'distance :445.7 km\ndatesource:', 'source': 'kiewit505'}
23
{'end': '2017-10-27T01:12:39', 'target': 'le-bataclan482', 'start': '1995-08-26T19:00:00', 'color': '#3f7f59', 'notes': 'distance :375.59 km\ndatesource:', 'source': 'richfield-avenue510'}
24
{'end': '2017-10-27T01:12:39', 'target': 'live-music-hall506', 'start': '1995-08-29T19:00:00', 'color': '#3f7f59', 'notes': 'distance :400.38 km\ndatesource:', 'source': 'le-bataclan482'}
25
{'end': '2017-10-27T01:12:39', 'target': 'steinberggasse478', 'start': '1995-08-31T19:00:00', 'color': '#3f7f59', 'notes': 'distance :406.96 km\ndatesource:', 'source': 'live-music-hall506'}
26
{'end': '2017-10-27T01:12:39', 'target': 'manchester-academy53-2', 'start': '1995-09-01T19:00:00', 'color': '#3f7f59', 'notes': 'distance :1022.19 km\ndatesource:', 'source': 'steinberggasse478'}
27
{'end': '2017-10-27T01:12:39', 'target': 'the-masquerade33-84', 'start': '1995-09-05T19:00:00', 'color': '#3f7f59', 'notes': 'distance :6583.12 km\ndatesource:', 'source': 'manchester-academy53-2'}
28
{'end': '2017-10-27T01:12:39', 'target': 'numbers29-95', 'start': '1995-09-07T19:00:00', 'color': '#3f7f59', 'notes': 'distance :1131.96 km\ndatesource:', 'source': 'the-masquerade33-84'}
29
{'end': '2017-10-27T01:12:39', 'target': 'club-dv840-111', 'start': '1995-09-10T19:00:00', 'color': '#3f7f59', 'notes': 'distance :1930.65 km\ndatesource:', 'source': 'numbers29-95'}
30
{'end': '2017-10-27T01:12:39', 'target': 'bogies43-116', 'start': '1995-09-14T19:00:00', 'color': '#3f7f59', 'notes': 'distance :476.64 km\ndatesource:', 'source': 'club-dv840-111'}
31
{'end': '2017-10-27T01:12:39', 'target': 'lupo-s-heartbreak-hotel41-71', 'start': '1995-09-15T19:00:00', 'color': '#3f7f59', 'notes': 'distance :3629.34 km\ndatesource:', 'source': 'bogies43-116'}
#3f597f

**Comment by ungentilgarcon** [comment]
(this list is taken from Foofighters ...6  where i tried to implement edge dates.

The one we are concerned with is the same lenght, only without edge date.

**Comment by ungentilgarcon** [comment]
![capture d ecran de 2017-10-27 10-47-37](https://user-images.githubusercontent.com/6549562/32095752-8513e0ec-bb04-11e7-8cba-6219f494c64b.png)

As you can see, bogart node is not created while it should be there, between mississipi and masquerade :

Node:
'bogart-s39-84': {'data': {'start': '1995-04-19T19:00:00', 'end': '1995-08-20T19:00:00', 'name': 'bogart-s', 'weight': 2.0, 'lat': 39.129952, 'lng': -84.509613, 'id': 'bogart-s39-84', 'color': '#3f7f59'}}

2
{'end': '2017-10-27T01:12:39', 'target': 'bogart-s39-84', 'start': '1995-04-18T19:00:00', 'color': '#727f3f', 'notes': 'distance :495.3 km\ndatesource:', 'source': 'mississippi-nights38-90'}
3
{'end': '2017-10-27T01:12:39', 'target': 'masquerade33-84', 'start': '1995-04-19T19:00:00', 'color': '#727f3f', 'notes': 'distance :596.99 km\ndatesource:', 'source': 'bogart-s39-84'}



Or am I doing something wrong?

**Comment by clemsos** [comment]
Looking at the data : your bogart node start on April 1995 and ends in August 1995 while edges end in 2017. When you try to get data from 1995 to 2017 there is no bogart node. Isn't that expected behavior ?

Also  : how do filter edges ? where is the code used to filter edges ?

**Comment by clemsos** [comment]
Also : how can your edges last longer than your nodes ? It does not make sense to me.

**Comment by ungentilgarcon** [comment]
well, same behaviour occurs without edge dates set

**Comment by ungentilgarcon** [comment]
![capture d ecran de 2017-10-27 11-12-55](https://user-images.githubusercontent.com/6549562/32096804-d8045f9a-bb07-11e7-95ee-952d6ffc272b.png)

Well on the left is the graph with edge date, on the left, it is without.

Notice that there are the same (so edge date is not parsed), and there are missing nodes still : bogart starts on 1995-04 yet not shown while graph should cover till may 95

=> sorry, but BUG ;)

**Comment by ungentilgarcon** [comment]
same for black-cat

**Comment by clemsos** [comment]
Of course edge date is not parsed. Did you wrote a parser for it ? :question:

**Comment by clemsos** [comment]
Right now, you need selected dates to encompass the whole date diff of the node for it to be displayed. For instance if it starts in 1995-04 and ends in 1995-07 but you selected date is 1995-03 to  1995-06 the node won't be shown.

Check this function to see how date filtering is handled :  https://github.com/topogram/topogram/blob/165069ba9bafdbbf04b16450da0630edb69d8d15/imports/client/ui/pages/TopogramViewComponent.jsx#L265-L270

**Comment by ungentilgarcon** [comment]
Ok, but node date is parsed,

and same for lupo-s-heartbreak-hotel.

So 3 nodes not showing here on this graph while:
{'data': {'start': '1995-04-25T19:00:00', 'end': '2003-05-02T19:00:00', 'name': 'black-cat', 'weight': 4.0, 'lat': 38.891312, 'lng': -77.033653, 'id': 'black-cat38-77', 'color': '#727f3f'}}
{'data': {'start': '1995-04-29T19:00:00', 'end': '1999-09-09T19:00:00', 'name': 'lupo-s-heartbreak-hotel', 'weight': 5.0, 'lat': 41.823469, 'lng': -71.414161, 'id': 'lupo-s-heartbreak-hotel41-71', 'color': '#3f7f59'}}

**Comment by ungentilgarcon** [comment]
Doesn't seem to occur anymore

**Comment by ungentilgarcon** [comment]
Was dued to time handling issues
