### ISSUE TITLE
line 53 of GeoEdges.jsx contains a second return

### ISSUE THREAD

**Issue by ungentilgarcon** [topogram/topogram#178]
Which I guess is useless??

**Comment by ungentilgarcon** [comment]
was trying to add dash to geoedges, but saw this weirdness..

**Comment by clemsos** [comment]
I see nothing here  https://github.com/topogram/topogram/blob/4d4f8ba0ad1417a6abb0e934cd59428f8807f2ed/imports/client/ui/components/geoMap/GeoEdges.jsx#L53
