### ISSUE TITLE
Layout works poorly

### ISSUE THREAD

**Issue by clemsos** [topogram/topogram#44]
Layouts works poorly, despite optimization. We need a clean force layout that will optimize the redaing of the graph.

**Comment by clemsos** [comment]
Some notes : 

From @maxkfranz 

> Unfortunately, Meteor is severely lacking in a lot of package management features.  It doesn't support teams well, and so it makes it really difficult to support the extensions with direct Meteor packages.  The solution is to just use npm packages.  The main library will continue to have a Meteor package for convenience, but the extensions will not.

**Comment by clemsos** [comment]
tested with npm install in Meteor, real pain. have to import each of the packages, then browserify, then turn into an object to get them into the client

NPM out

**Comment by clemsos** [comment]
Tested with meteor Bower support : easier to install and update, better support. Have problems loading cola and arbor though because cola is not imported as "cola" so raise error "cola not found". Arbor is not on npm or bower anyway

**Comment by clemsos** [comment]
about the layouts 
- cola not working (stuck in dependencies hell !)
- arbor not working (stuck in dependencies hell !) 
- springy behaves weird
- spread gives ok results but is very slow to process (sth like 8000+ ms)
- cose-bilkent throw a "Uncaught TypeError: Cannot read property 'prototype' of undefined"

**Comment by clemsos** [comment]
So at the end, best choice will be 'spread' layout but need to investigate why it is so slow . It even freezes the browser.

**Comment by clemsos** [comment]
springy freezes the browser as well, so it may not be an issue related to spread layout

**Comment by maxkfranz** [comment]
It looks like Meteor should support npm : https://medium.com/@borellvi/meteor-meets-npm-a5cc48d90abe#.p58b9llhi

There's also this package : https://github.com/meteorhacks/npm

**Comment by clemsos** [comment]
Hey @maxkfranz , thanks for the feedback and sorry to reproduce your words online without even asking... Anyway, the problem with this Meteor npm support is that it is "available in the Server Side only" : https://github.com/meteorhacks/npm#api so I have to browserify all the packages to serve them client side, then I have to load each of them separately as a global object to be able to eventually add layouts to cy. Because of all this, Bower looks easier - as it has support for Meteor as well.

**Comment by maxkfranz** [comment]
Is using browserify really necessary?  All the packages are browserify/node-ready already, and they don't `require()` anything external.

**Comment by maxkfranz** [comment]
It also looks like Meteor is adding proper npm support in 1.3 (now beta).  If you want this for production right away, bower is probably better.

**Comment by clemsos** [comment]
thanks @maxkfranz . I ended up using bower with the `mquandalle:bower` package. I managed to get most of the packages to work

but no chance with cola  . The problem is load order and I think I have tried everything from npm, bower, copy/paste files in nested folders, etc Still, the cytoscape-cola will load before cola.js (the file is way smaller), so I can not manage to get it to work. Cola is properly loaded, but apparently after cytoscape-cola , so I get a "cola is undefined" error each time, even though I can access the cola object from the console. still investigating now

**Comment by clemsos** [comment]
![selection_067](https://cloud.githubusercontent.com/assets/743246/13043661/bd98e27e-d3c9-11e5-9cdd-942df87dc14b.png)

**Comment by clemsos** [comment]
so, some progresses. The strategy to load cola is as follow. I copy the original `cola.js` in some nested folder `./client/lib/layouts/cola.js` and I import `cytoscape-cola` with bower. Still some version-related errors 
- "cola is undefined" error with the v3.1.0
- "cola.adaptor is not a function " with v3.min.js or v2
- "Uncaught ReferenceError: cola is not defined" with the v1

**Comment by clemsos** [comment]
mmmm... just figured out that "Cola.js >= 3.1.2" is required by cytoscape-cola. Problem is that the release on github stops at 3.1.0

**Comment by clemsos** [comment]
ok npm has webcola 3.1.3 ! still get an "undefined error"

**Comment by clemsos** [comment]
ok let's say #64 solves it . closing for now
