### ISSUE TITLE
can not import graph data on new network creation !

### ISSUE THREAD

**Issue by clemsos** [topogram/topogram#74]
hoooooly cow, should be feature 101

**Comment by clemsos** [comment]
solved in 1f8044921ed7850e2b3af03ae9ac0fe5d98f8161

**Comment by ungentilgarcon** [comment]
yeah clem, 

j'aime quand tu fais du topo :) 

----- Mail original -----

De: "Clément Renaud" notifications@github.com 
À: "topogram/topogram-client" topogram-client@noreply.github.com 
Envoyé: Jeudi 2 Juin 2016 09:50:37 
Objet: Re: [topogram/topogram-client] can not import graph data on new network creation ! (#74) 

solved in 1f80449

**Comment by clemsos** [comment]
Ben ouais, ça me fait bien plaisir aussi  !

**Comment by ungentilgarcon** [comment]
Si je pouvais je t'aiderai, 

dès que je peux -semaine pro- je t'aide 

----- Mail original -----

De: "Clément Renaud" notifications@github.com 
À: "topogram/topogram-client" topogram-client@noreply.github.com 
Cc: "gregory bahde" gregory.bahde@laposte.net, "Comment" comment@noreply.github.com 
Envoyé: Jeudi 2 Juin 2016 10:32:32 
Objet: Re: [topogram/topogram-client] can not import graph data on new network creation ! (#74) 

Ben ouais, ça me fait bien plaisir aussi !

**Comment by clemsos** [comment]
T'inquiètes! Faut qu'on se refasse des bonnes sessions de topo de toutes façons :)
