### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by clemsos** [topogram/topogram#84]
We need a good landing page so people can see what topogram is, how it works
... or even only access topogram #82

**Comment by clemsos** [comment]
what is the call to action ? register ? download ?

**Comment by clemsos** [comment]
related to documentation #83 and topogram/topogram.github.io#6

**Comment by eallenOP** [comment]
I have some students looking for projects they can help with documentation and things. They start next month. Is there some way they can help you?

**Comment by clemsos** [comment]
Hello @eallenOP.  

Sure, that will be great. There are many parts in this project that need improvements and reflections. I will be glad to show them around and see how we can find something to work on together. 

We can continue this discussion by email  hi@topogram.io, on Slack https://topogram.slack.com or here, as you prefer. 
Looking forward !

**Comment by eallenOP** [comment]
Excellent! Once I have the students ready to go I'll send them here to see what you'd like them to help with. Thank you very much.

**Comment by clemsos** [comment]
here is a new landing page with basic content for now http://topogram.io
